AWSTemplateFormatVersion: "2010-09-09"
Description: "Basic network setup with VPC and subnets"

Parameters:
  EnvironmentName:
    Type: String 
    Description: "Name of the environment"
  VpcCidrBlock:
    Type: String
    Description: "CIDR block for the VPC"
  PublicSubnet1CidrBlock:
    Type: String
    Description: "CIDR block for public subnet 1"
  PublicSubnet2CidrBlock:
    Type: String
    Description: "CIDR block for public subnet 2" 
  PublicSubnet3CidrBlock:
    Type: String
    Description: "CIDR block for public subnet 3"
  PrivateSubnet1CidrBlock:
    Type: String
    Description: "CIDR block for private subnet 1"
  PrivateSubnet2CidrBlock:
    Type: String
    Description: "CIDR block for private subnet 2"
  PrivateSubnet3CidrBlock:
    Type: String
    Description: "CIDR block for private subnet 3"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-vpc"

  PublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 0, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PublicSubnet1CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-public-subnet1"

  PublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 1, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PublicSubnet2CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-public-subnet2"

  PublicSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 2, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PublicSubnet3CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-public-subnet3"

  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 0, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PrivateSubnet1CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-private-subnet1"

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 1, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PrivateSubnet2CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-private-subnet2"

  PrivateSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref "VPC"
      AvailabilityZone: !Select [ 2, !GetAZs "us-east-1" ]
      CidrBlock: !Ref PrivateSubnet3CidrBlock
      Tags:
        - Key: "Name"
          Value: !Sub "${EnvironmentName}-private-subnet3"

Outputs:
  VPC:
    Description: "VPC ID"
    Value: !Ref "VPC"
    Export:
      Name: !Sub "${EnvironmentName}-vpc"

  PublicSubnet1:
    Description: "Public Subnet 1 ID"
    Value: !Ref "PublicSubnet1"
    Export:
      Name: !Sub "${EnvironmentName}-public-subnet-1"

  PublicSubnet2:
    Description: "Public Subnet 2 ID"
    Value: !Ref "PublicSubnet2"
    Export:
      Name: !Sub "${EnvironmentName}-public-subnet-2"

  PublicSubnet3:
    Description: "Public Subnet 3 ID"
    Value: !Ref "PublicSubnet3"
    Export:
      Name: !Sub "${EnvironmentName}-public-subnet-3"

  PrivateSubnet1:
    Description: "Private Subnet 1 ID"
    Value: !Ref "PrivateSubnet1"
    Export:
      Name: !Sub "${EnvironmentName}-private-subnet-1"

  PrivateSubnet2:
    Description: "Private Subnet 2 ID"
    Value: !Ref "PrivateSubnet2"
    Export:
      Name: !Sub "${EnvironmentName}-private-subnet-2"

  PrivateSubnet3:
    Description: "Private Subnet 3 ID"
    Value: !Ref "PrivateSubnet3"
    Export:
      Name: !Sub "${EnvironmentName}-private-subnet-3"